name: Puppeteer scripts  sync
run-name: ${{ github.actor }} is syncing puppeteer example scripts
on: 
  push:
    branches:
      - main
    paths: 
      - 'scriptExamples.js'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."