name: Puppeteer scripts  sync
run-name: ${{ github.actor }} is syncing puppeteer example scripts
on: 
  push:
    branches:
      - main
    paths: 
      - 'scriptExamples.js'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pushes scriptExamples.js to the repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'scriptExamples.js'
          destination_repo: 'hasan-wajahat/temp'
          destination_branch: 'master'
          user_email: 'hasan_wajahat@hotmail.com'
          user_name: 'hasan-wajahat'
          commit_message: 'syncing scriptExamples.js'